INSERT INTO SUBBREDDITS  (SUBREDDIT_ID , name) VALUES (1, 'almafa');
INSERT INTO SUBBREDDITS  (SUBREDDIT_ID , name) VALUES (2, 'hajrafradi');

INSERT INTO REDDIT_USER  (USER_ID, PASSWORD, REGISTRATION_DATE, USER_ROLE, USERNAME) VALUES (1, 'asd', '1998-12-02', 'NORMAL', 'asd');
INSERT INTO REDDIT_USER  (USER_ID, PASSWORD, REGISTRATION_DATE, USER_ROLE, USERNAME) VALUES (2, 'peti', '1998-12-02', 'MODERATOR', 'jelszo');

INSERT INTO REDDIT_POST  (POST_ID, CONTENT, CREATED_AT, TITLE, PIC, VOTES, PARENT_ID, USER_ID) VALUES (1, 'quality content', '2019-11-09', 'first post', null,  1, 2, 1);
INSERT INTO REDDIT_POST  (POST_ID, CONTENT, CREATED_AT, TITLE, PIC, VOTES, PARENT_ID, USER_ID) VALUES (2, 'quality content2', '2019-11-09', 'second post', 'https://picsum.photos/200/300',  2, 1, 1);

INSERT INTO SUBBREDDITS_OWNERS  (SUBREDDIT_ID , USER_ID ) VALUES (1, 2);
INSERT INTO SUBBREDDITS_OWNERS  (SUBREDDIT_ID , USER_ID ) VALUES (2, 2);

INSERT INTO SUBBREDDITS_SUBSCRIBERS  (SUBREDDIT_ID, USER_ID ) VALUES (1, 1);
INSERT INTO SUBBREDDITS_SUBSCRIBERS  (SUBREDDIT_ID, USER_ID ) VALUES (1, 2);
INSERT INTO SUBBREDDITS_SUBSCRIBERS  (SUBREDDIT_ID, USER_ID ) VALUES (2, 1);
INSERT INTO SUBBREDDITS_SUBSCRIBERS  (SUBREDDIT_ID, USER_ID ) VALUES (2, 2);

INSERT INTO COMMENT  (COMMENT_ID, TEXT, VOTES, POST_ID, USER_ID) VALUES (1, 'nice', 1, 1, 2);
INSERT INTO COMMENT  (COMMENT_ID, TEXT, VOTES, POST_ID, USER_ID) VALUES (2, 'nice', 1, 1, 2);